#ifndef TCLOCK_VERSION_H
#define TCLOCK_VERSION_H

#define TCLOCK_VER_MAJOR 1
#define TCLOCK_VER_MINOR 0
#define TCLOCK_VER_PATCH 0
#define TCLOCK_VER_BUILD 0

#define TCLOCK_VER_FILE_NUM TCLOCK_VER_MAJOR,TCLOCK_VER_MINOR,TCLOCK_VER_PATCH,TCLOCK_VER_BUILD
#define TCLOCK_VER_FILE_STR "1.0.0.0"
#define TCLOCK_VER_PRODUCT_STR "1.0.0.0"

#endif /* TCLOCK_VERSION_H */
