#ifndef TCLOCK_VERSION_H
#define TCLOCK_VERSION_H

#define TCLOCK_VER_MAJOR 0
#define TCLOCK_VER_MINOR 2
#define TCLOCK_VER_PATCH 5
#define TCLOCK_VER_BUILD 4

#define TCLOCK_VER_FILE_NUM TCLOCK_VER_MAJOR,TCLOCK_VER_MINOR,TCLOCK_VER_PATCH,TCLOCK_VER_BUILD
#define TCLOCK_VER_FILE_STR "0.2.5.4"
#define TCLOCK_VER_PRODUCT_STR "0.2.5.4"

#endif /* TCLOCK_VERSION_H */
